eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080      
spring:
  boot:
    admin:
      client:
        url: [http://localhost:6543]
  application:
    name: JWT-SERVICE
  data:
    mongodb:
      authentication-database: admin
      database: test
      host: localhost
      port: 27017
               
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always      
        
      
