server:
  port: 7171

eureka:
  instance:
   hostname: localhost:8761

spring:
  boot:
    admin:
      client:
        url: [http://localhost:6543]
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: CONSUMER-SERVICE
          uri: http://localhost:9090/
          predicates:
            - Path=/api/**       
            
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always                      
            
            